FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_DEFAULT_TIMEOUT=1000

COPY apps/ml/requirements.txt .

RUN pip install --no-cache-dir --retries 10 --default-timeout=1000 -r requirements.txt

COPY apps/ml/ .

RUN python train_models.py

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]